version: '3.6'
services:
  java:
    image: openjdk:17
    ports:
      - 5050:5050
    tty: true
    volumes:
      - ./java:/srv:cached
    working_dir: /srv
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: $POSTGRESUSER
      POSTGRES_PASSWORD: $POSTGRESPASSWORD
      POSTGRES_DB: dev_db
    volumes:
      - expenditure_data:/var/lib/postgresql/data
    hostname: postgres
    network_mode: "host" 
volumes:
  expenditure_data:
    driver: local
